name: Mangos
favicon: null
layout_spectrum: 0.00993
typography_spectrum: 0
title: Mangos Belize
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a9a5a0'
    - '#006948'
    - '#c03000'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
